In [2]:
import numpy as np
np.array([1,2,3,4])


array([1, 2, 3, 4])

In [4]:
l=[1,3,4,53,2]
# converting list into array
np.array(l)

array([ 1,  3,  4, 53,  2])

In [5]:
# converting a list where 1 have decimal value so can whole number will convert into float

l=[1.2, 34,54,3]
np.array(l)

array([ 1.2, 34. , 54. ,  3. ])

In [36]:
# 2D array
l=[[69,3,12],[34,15,66],[27,78,49]]
arr=np.array(l)
arr

array([[69,  3, 12],
       [34, 15, 66],
       [27, 78, 49]])

In [37]:
# shapes in array attributes
arr.shape


(3, 3)

In [38]:
arr.dtype

dtype('int64')

In [39]:
arr

array([[69,  3, 12],
       [34, 15, 66],
       [27, 78, 49]])

In [ ]:
np.sum(arr,axis=0)
#sum by column [69+34+27,3+15+78,12+66+49] axis=0 means sum by column

array([130,  96, 127])

In [41]:
arr

array([[69,  3, 12],
       [34, 15, 66],
       [27, 78, 49]])

In [ ]:
np.sum(arr,axis=1)
# sum by row [69+3+12,34+15+78,27+78+49]

array([ 84, 115, 154])

In [44]:
arr.mean()

np.float64(39.22222222222222)

In [ ]:
# Its return max value of index number so 78 is a maximum value or it's index value of 7
arr.argmax()

np.int64(7)

In [47]:
#It return min value is 3 so the index number is 1 
arr.argmin()

np.int64(1)

Array indexing and slicing

In [19]:
arr2=np.arange(11,21)
arr2

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [22]:
arr2[9]

np.int64(20)

Slicing array

In [23]:
arr2[2:7]

array([13, 14, 15, 16, 17])

In [24]:
arr2[:5]

array([11, 12, 13, 14, 15])

In [26]:
arr2[2:]

array([13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
arr3=np.arange(1,31).reshape(6,5)
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [29]:
arr3[5]

array([26, 27, 28, 29, 30])

Selection of particular 2D matrix

In [30]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [33]:
slice=arr3[3:,3:]
slice

array([[19, 20],
       [24, 25],
       [29, 30]])

In [35]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

How to select specific column

In [34]:
arr3[:,2]

array([ 3,  8, 13, 18, 23, 28])